name: Archers
main: TechGuard.x1337x.Archers.Archers
version: 2.0
description: Advanced Archers only!
authors:
  - TechGuard
  - x1337x
commands:
  arrow:
     description: Display a list of arrows
     usage: /<command> [arrowname]
  archers:
     description: Shows the archers commands
     usage: /<command> help