name: Archers

main: TechGuard.Archers.Archers

version: 0.1

description: Advanced Archers only!

authors:
  - TechGuard
 
          - x1337x
commands:
  arrow:
     description: Display a list of arrows
     usage: /<command> [arrowname]