name: Archers
main: TechGuard.x1337x.Archers.Archers
version: b5
description: Advanced Archers only!
depend: [Permissions, BukkitContrib]
authors:
  - TechGuard
  - x1337x
commands:
  arrow:
     description: Display a list of arrows
     usage: /<command> [arrowname]
  archers:
     description: Shows the archers commands
     usage: /<command>